### ISSUE TITLE
error 255 on laucnh

### ISSUE THREAD

**Issue by testc2n14** [Meister1593/ADBForwarder#3]
this is the rror i get when running from terminal 
```c2n14@fedora:~$ /home/c2n14/adbforwarder/ADBForwarder
Platform: Linux
Starting ADB Server...
Unhandled exception. SharpAdbClient.Exceptions.AdbException: The adb process returned error code 255 when running command start-server
   at SharpAdbClient.AdbCommandLineClient.RunAdbProcess(String command, List`1 errorOutput, List`1 standardOutput)
   at SharpAdbClient.AdbCommandLineClient.StartServer()
   at SharpAdbClient.AdbServer.StartServer(String adbPath, Boolean restartServerIfNewer)
   at ADBForwarder.Program.Main()
Aborted (core dumped)
c2n14@fedora:~$ 
```

**Comment by RealMoosey** [comment]
Currently getting this error when trying to start. Was there a fix to this somewhere?

**Comment by testc2n14** [comment]
i don't rember what i did give me some time to check

**Comment by RealMoosey** [comment]
Found out it spits out the error when i plug in the headset with the usb, if that helps :)

**Comment by testc2n14** [comment]
affter joigging my emmeory i think it;s a timing issue i rember having to have my q3 headset on the desk so i could put it on so i could accpect the prompt fast enough, that might have been becuase of soemthing else tho

**Comment by testc2n14** [comment]
yeah affter checking i made this .sh file for the adb thingy prolly becuase i was sick of it not working 
```
#!/usr/bin/env bash
cd /home/c2n14/drives/bulkstorage/Downloads/"New Folder"
adb start-server
adb forward tcp:9943 tcp:9943
adb forward tcp:9944 tcp:9944
printf "Press return to exit..." && read -r
adb kill-server
```

**Comment by Meister1593** [comment]
Not sure if i understand root cause, definitely need more info

**Comment by Meister1593** [comment]
Can someone of you who had this issue try latest build again and see if it works?
https://github.com/alvr-org/ADBForwarder/actions/runs/10403243630/artifacts/1815453943

**Comment by RealMoosey** [comment]
Sadly im not on my linux os for now.
But i can tell you the error went away the moment i installed ADB via the synaptic package manager.

**Comment by BogTheMudWing** [comment]
> Can someone of you who had this issue try latest build again and see if it works? https://github.com/alvr-org/ADBForwarder/actions/runs/10403243630/artifacts/1815453943

This starts correctly on Linux Mint 22.

**Comment by wereretot** [comment]
It throws this error when running on Manjaro Linux

You must install .NET to run this application.

App: /home/rexommendation/Programs/ADBForwarder-linux-x64/ADBForwarder
Architecture: x64
App host version: 8.0.8
.NET location: Not found

Learn more:
https://aka.ms/dotnet/app-launch-failed

Download the .NET runtime:
https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=linux-x64&os=manjaro&apphost_version=8.0.8

**Comment by Meister1593** [comment]
> It throws this error when running on Manjaro Linux
> 
> You must install .NET to run this application.
> 
> App: /home/rexommendation/Programs/ADBForwarder-linux-x64/ADBForwarder Architecture: x64 App host version: 8.0.8 .NET location: Not found
> 
> Learn more: https://aka.ms/dotnet/app-launch-failed
> 
> Download the .NET runtime: https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=linux-x64&os=manjaro&apphost_version=8.0.8

Is this full log?

**Comment by wereretot** [comment]
Yeah, it's what the application throws when I attempt to run
https://github.com/alvr-org/ADBForwarder/actions/runs/10403243630/artifacts/1815453943

**Comment by slxdy** [comment]
Built from main, same exception

**Comment by slxdy** [comment]
Ah. The solution is to run it as root

**Comment by EdwinKM** [comment]
the same error, starting as root fixed it indeed. Please update the documentation

**Comment by slxdy** [comment]
Or rather add a proper error message for missing perms

**Comment by JunzheJosephZhu** [comment]
This is a Udev rule issue
I ran into a similar issue and wound up resolving it by making a Udev rule,
sudo nano /etc/udev/rules.d/00-all-usb.rules
```
SUBSYSTEM=="usb", MODE="0666"
```
or running ADBForwarder in sudo
